name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  install:
    name: Installation des dépendances
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Restaurer le cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Installer les dépendances
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

  format-lint:
    name: Formatage & Lint
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Restaurer le cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Vérifier le formatage (Prettier)
        run: npm run format:check

      - name: Analyser le code (ESLint + SonarJS)
        run: npm run lint

  tests:
    name: Tests unitaires
    runs-on: ubuntu-latest
    needs: [format-lint]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Restaurer le cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Lancer les tests avec couverture
        run: npm run test:ci

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Restaurer le cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Compiler l'application
        run: npm run build

  security:
    name: Scan de sécurité (Trivy)
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v4

      - name: Installer Trivy
        # On change "/usr/local/bin" par "." pour installer localement dans le dossier du projet
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b .

      - name: Scanner les dépendances npm
                # On ajoute "./" devant trivy pour exécuter le binaire fraîchement téléchargé ici
        run: ./trivy fs --exit-code 0 --severity CRITICAL,HIGH --no-progress .
